### ISSUE TITLE
Choosing NOTYD gives an error when ordering multiple combinations from the same product

### ISSUE THREAD

**Issue by muyncky** [paynl/prestashop16-plugin#22]
## Describe the bug

When multiple combination products are ordered, NOTYD cannot be used. The technical error “duplicated product id” appears in the logs of PAY. Merchants cannot access this information.

---

## Expected behavior

Use the id of the combination to identify products. Or use the product id and combination id. Like 100.3 with a dot, or 100_3 with an underscore, just an idea.

---

## Steps to Reproduce

- Go to a product with combinations/variations (product attributes)
- Add one variant
- Add another variant
- Continue with the checkout, and choose NOTYD
- See error

**Comment by woutse** [comment]
Thanks for your message, we'll look into it!

**Comment by muyncky** [comment]
@woutse

Do you have an update for us about this issue?

**Comment by woutse** [comment]
Hi, thanks for your message. A release is on its way with a fix for this issue. So your PR will be closed.

**Comment by coMegaWebMaster** [comment]
Hi, I do not why this should be only for NOTYD, but after the update I only see ID's no more product names. I update the code to this so that it is always adding the attribute ID and name correctly:
/modules/paynl_paymentmethods/controllers/front/payment.php
Line 169
`            /**
             * @var $cart CartCore
             */
            $products = $cart->getProducts();
            foreach ($products as $product) {
                $taxClass = Pay_Helper::calculateTaxClass($product['price_wt'], $product['price_wt'] - $product['price']);
                $taxPercentage = $this->calculateTaxPercentage($product['price_wt'], $product['price']);
                $apiStart->addProduct($product['id_product'] **. '_' . $product['id_product_attribute']**, **$product['attributes'] . '_' .** $product['name'], round($product['price_wt'] * 100), $product['cart_quantity'], $taxClass, $taxPercentage);
            }`

Even better is to set `$product['attributes'] . '_' . $product['name']` to `$product['reference'] . '_' . $product['name']` as only 46 characters are allowed in the paynl system, this way clients can always find the product.
